ALTER TABLE token_usage ADD COLUMN context_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE token_usage ADD COLUMN context_window INTEGER NOT NULL DEFAULT 0;
ALTER TABLE token_usage ADD COLUMN cached_tokens INTEGER NOT NULL DEFAULT 0;
